name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via git pull on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            # клон (якщо ще нема) або хард-оновлення з main
            if [ ! -d /home/ubuntu/db/.git ]; then
              cd /home/ubuntu
              git clone https://github.com/Tuchechka/db.git db
            else
              cd /home/ubuntu/db
              git fetch origin main
              git reset --hard origin/main
            fi

            # залежності
            cd /home/ubuntu/db/app
            if [ ! -d venv ]; then python3 -m venv venv; fi
            source venv/bin/activate
            pip install --upgrade pip setuptools wheel
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            deactivate

            # рестарт сервісу
            sudo systemctl daemon-reload
            sudo systemctl restart flaskapp
            sleep 2
            sudo systemctl --no-pager -l status flaskapp

      - name: Healthcheck
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            # якщо у тебе нема роута "/", заміни на реальний (напр. /apidocs чи /health/db)
            curl -sf http://127.0.0.1:5000/ || echo "No root route (that's OK if you don't have one)"
